name: Game deploy

on:
    push:
jobs:
  Build:
    strategy:
      # Using matrix build even if not needed
      matrix:
        os: [ ubuntu-latest ]
        jvm_version: [ 11 ]
    runs-on: ${{ matrix.os }}
    env:
      JAVA_VERSION: ${{ matrix.jvm_version }}
      OS: ${{ matrix.os }}
      TERM: dumb
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Fetch tags
        shell: bash
        run: git fetch --tags -f
      - name: Setup Scala with Java ${{ matrix.jvm_version }}
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.${{ matrix.java }}
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: Sbt test
        run: sbt test
      - name: Build project
        run:  sbt -v "project js; fastOptJS"
      - name: Adjust folders for deployment
        shell: bash
        run: .github/scripts/adjust-deployment.sh
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public